### ISSUE TITLE
Dynamic space classes

### ISSUE THREAD

**Issue by aimen-zenasni** [sitetent/tentcss#10]
In some files we have some repetitive space classes like in the `_margin.scss` :

```
    &-xxxs { margin: rem($space-xxxs); }
    &-xxs { margin: rem($space-xxs); }
    &-xs { margin: rem($space-xs); }
    &-sm { margin: rem($space-sm); }
    &-md { margin: rem($space-md); }
    &-lg { margin: rem($space-lg); }
    &-xl { margin: rem($space-xl); }
    &-xxl { margin: rem($space-xxl); }
    &-xxxl { margin: rem($space-xxxl); }
```

I want to add some loops to avoid it and make the code more maintainable, it will look like this :

`_variables-defaults.scss`
```
$spaces: (
  xxxs: $space-xxxs,
  xxs: $space-xxs,
  xs: $space-xs,
  sm: $space-sm,
  md: $space-md,
  lg: $space-lg,
  xl: $space-xl,
  xxl: $space-xxl,
  xxxl: $space-xxxl
);
```

`_margin.scss`
```
@each $space, $margin in $spaces {
    &-#{$space} {
        margin: rem($margin);
    }
}
```

What do you think about it ?

**Comment by ulinaaron** [comment]
Interesting proposal, it would certainly source-ify the code. My only concern with this approach is that there are already `$space-*` variables in `_variables-defaults.scss`. Wouldn't this cause some duplication too?

So in theory we would have:

```

$space-xxxs: ($space-base) !default;
$space-xxs: ($space-base * 2) !default;
$space-xs: ($space-base * 3) !default;
$space-sm: ($space-base * 4) !default;
$space-md: ($space-base * 5) !default;
$space-lg: ($space-base * 6) !default;
$space-xl: ($space-base * 7) !default;
$space-xxl: ($space-base * 8) !default;
$space-xxxl: ($space-base * 9) !default;

$spaces: (
  xxxs: $space-xxxs,
  xxs: $space-xxs,
  xs: $space-xs,
  sm: $space-sm,
  md: $space-md,
  lg: $space-lg,
  xl: $space-xl,
  xxl: $space-xxl,
  xxxl: $space-xxxl
);
```

We could ditch the current space classes all together and use your new approach for handling them altogether:

```
$spaces: (
  xxxs: ($space-base),
  xxs: ($space-base * 2),
  xs: ($space-base * 3),
  sm: ($space-base * 4), 
  md: ($space-base * 5),
  lg: ($space-base * 6),
  xl: ($space-base * 7),
  xxl: ($space-base * 8),
  xxxl: ($space-base * 9)
) !default;
```

This would certainly be less confusing and if a developer decided to modify the keys in the map classes would automatically be created because of the `@each` loop you are proposing.

The biggest issue with this is now all the space variables are stuck inside a Sass map and I think using `map-get($spaces, md);` would be tedious to use. We could create a `space()` similar to that shown in this article with `color()`: https://codepen.io/jakealbaugh/post/using-sass-functions-to-access-complex-variable-maps. 

However it still presents a new type of convention to using properties which isn't standard to the normal variable usage. Which I would be okay with, I just wonder if then we should make more functions that get properties from Sass maps.

**Comment by aimen-zenasni** [comment]
I'm agree with you, we shouldn't duplicate the variables in `_variables-defaults.scss`.

Personnally, i don't think that `map-get()` is hard to deal with, it's just a basic function that allows to access to a key or a value, as the `color ()` function in the article. The real power of the `color()` is that it can handle nested maps.

For now they are no nested maps in the project, i think we can use `map-get()` for the moment, no ?

**Comment by ulinaaron** [comment]
Solid point on the `map-get()` usage, I think that would be fine to use for most cases of maps.  I'll start working on a branch for this soon.

Thanks for the feedback!

**Comment by aimen-zenasni** [comment]
I'm happy to contribute :+1:

**Comment by ulinaaron** [comment]
This has been addressed by release v.1.4.1
